version: 2
jobs:
  build:
    docker:
      - image: golang
    working_directory: /go/src/github.com/emvicom/hide
    steps:
      - checkout
      - go get github.com/speps/go-hashids
      - run: go test -cover .
